### ISSUE TITLE
merge jemalloc-ctl into jemallocator?

### ISSUE THREAD

**Issue by sfackler** [gnzlbg/jemallocator#50]
https://github.com/sfackler/jemalloc-ctl provides a typed interface to the diagnostic/control features jemalloc supports. Currently, it just asserts that the right symbols exist, but once global allocators stabilize it seems like it'd make way more sense for these APIs to live in the allocator crate itself.

Seem reasonable? I can make a PR if so.

**Comment by gnzlbg** [comment]
`jemalloc-sys` should already be exporting all symbols that `jemalloc-ctl` needs, and `jemallocator` re-export these via its `ffi` module, so `jemalloc-ctl` could just add any of these crates as a dependency and use those. Are some symbols missing?

I don't mind exposing here a type-safe wrapper over the control features, but I could understand that others might want to keep this crate "thin". 

In any case refactoring `jemalloc-ctl` to depend on `jemallocator` seems to be a good idea anyways, and should make it easier to move its functionality into this crate.

**Comment by sfackler** [comment]
Looks like jemalloc-sys already exposes everything we need - I'll update to depend on jemalloc-sys.

**Comment by gnzlbg** [comment]
FWIW I am a bit worried here again (cc @SimonSapin ). 

Only the final binary or the crate that sets the global allocator can use `jemalloc-ctl` because no other crate can know / query which global allocator is being used neither at compile-time nor run-time.

Thinking a bit about how we could do this, we don't actually know from just looking at the dependency graph if there is one crate setting the global allocator. We only know when we actually compile that particular crate which means that this is not something that can be used statically.

Did we consider to require a crate that sets a global allocator to be a special crate type? 

For example, we could have a `jemalloc-global` crate that just contains the couple of lines that set jemalloc as the global allocator, and those who want to use it just need to depend on that crate. If that were a special crate type, we would know exactly that the global allocator is `jemalloc-global`, and could define a `cfg(global_alloc = "jemalloc-global")` for the whole dependency graph from the beginning, which would allow crates to conditionally depend on `jemalloc-ctl`. This could also allow us to diagnose if two crates try to set the global allocator very early on before actually having compiled anything. It could even allow us to not have to wait till link time to resolve the allocator symbols.

**Comment by gnzlbg** [comment]
> I don’t see why the global allocator is relevant at all. Depending on jemalloc-ctl causes jemalloc to be linked and it controls / provides diagnostics for allocations made by jemalloc, which may or may not include those requested by e.g. Vec<T>.

Can the following happen? 

crate `A` depends on `jemalloc-ctl`, which depends on some version of `jemalloc-sys` that links `jemalloc 4.x`. crate `B` depends on crate A and some version of `jemallocator`, which depends on a different major `jemalloc-sys` version, linking `jemalloc 5.x`, and uses that to set the global allocator.

> Modulo #19, it should be possible to use jemallocator without registering it as global.

Good point.

> I don’t see why the global allocator is relevant at all.

Say I have a middleware library that can log some stuff. And if the global allocator is jemalloc, I'd like to use `jemalloc-ctl` to log some stuff. How can this library detect at compile-time and run-time if the global allocator is jemalloc?

In particular, I wonder whether it makes sense for `jemalloc-ctl` to require `jemalloc` to be linked. It might make more sense to use `dlsym` or weak symbols to detect at run-time whether jemalloc is the global alloc and return `Err` if it isn't.

This dynamic libraries to link different crates like `jemalloc-ctl` for different allocators, and choose the appropriate one dynamically depending on which allocator is dynamically linked to a rust binary.

**Comment by SimonSapin** [comment]
Because of `links` in `Cargo.toml` https://github.com/alexcrichton/jemallocator/blob/0.1.7/jemalloc-sys/Cargo.toml#L6, Cargo won’t let you build two versions of jemalloc-sys in the same dependency graph. And if you remove that you’d most likely get linker errors for duplicate symbols.

> How can this library detect at compile-time and run-time if the global allocator is jemalloc?

I believe it cannot, but I don’t know if that is a problem that needs solving. This library can have Cargo feature flags to allow its users to select different functionality.

**Comment by gnzlbg** [comment]
> Because of links in Cargo.toml https://github.com/alexcrichton/jemallocator/blob/0.1.7/jemalloc-sys/Cargo.toml#L6, Cargo won’t let you build two versions of jemalloc-sys in the same dependency graph. And if you remove that you’d most likely get linker errors for duplicate symbols.

Nice, thanks, this makes sense.

> This library can have Cargo feature flags to allow its users to select different functionality.

This means that every library that uses it would need to re-export those features, can be done, but feels a bit clunky.

**Comment by sfackler** [comment]
Some badness can apparently happen with a stdlib-provided jemalloc and jemalloc-sys provided jemalloc: #51.

**Comment by gnzlbg** [comment]
> Seem reasonable? I can make a PR if so.

Please do so whenever you can.
